# Generated by Django 4.2.3 on 2023-08-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/')),
                ('name', models.CharField(max_length=40)),
                ('brand', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
