# Generated by Django 4.2.3 on 2023-08-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_comment_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='antimalaria', max_length=40),
            preserve_default=False,
        ),
    ]
