# Generated by Django 4.2.3 on 2023-08-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
