# Generated by Django 4.2.3 on 2023-09-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_healthtipcategory_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(default='others', max_length=40, unique=True),
        ),
    ]
