# Generated by Django 4.2.3 on 2023-08-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_unit_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='images/IMG_1828_2.jpeg', upload_to='images/')),
                ('title', models.CharField(max_length=40)),
                ('body', models.TextField()),
            ],
        ),
    ]
