# Generated by Django 4.2.3 on 2023-08-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_healthtips_healthtip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthtip',
            name='category',
            field=models.CharField(default='general', max_length=40),
            preserve_default=False,
        ),
    ]
